namespace: test
replicaCount: 1

image:
  repository: test
  tag: test
  imagePullPolicy: IfNotPresent

label:
  app: test
  env: test
  team: test
containerPort: 8080

enable:
  env: true

env:
  - name: Hello
    value: "world"
  - name: foo
    value: "bar"
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 0.5
    memory: 300Mi
  requests:
    cpu: 0.5
    memory: 300Mi

restartPolicy: Always
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

ambassador:
  url: example.com

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60
  
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 60
  
hpa:
  targetCPUUtilizationPercentage: 50
  minReplicas : 1
  maxReplicas: 5
